#!/bin/env ruby
# encoding: utf-8

require 'csv'

 l = [ "LA CEIBA", "EL PORVENIR", "ESPARTA", "JUTIAPA", "LA MASICA", "SAN FRANCISCO", "TELA", "ARIZONA", "TRUJILLO", "BALFATE", "IRIONA", "LIMON", "SABA", "SANTA FE", "SANTA ROSA AGUAN", "SONAGUERA", "TOCOA", "BONITO ORIENTAL", "COMAYAGUA", "AJUTERIQUE", "EL ROSARIO", "ESQUIAS", "HUMUYA", "LA LIBERTAD", "LAMANI", "LA TRINIDAD", "LEJAMANI", "MEAMBAR", "MINAS DE ORO", "OJOS DE AGUA", "SAN JERONIMO", "SAN JOSE DE COMAYAGUA", "SAN JOSE DEL POTRERO", "SAN LUIS", "SAN SEBASTIAN", "SIGUATEPEQUE", "VILLA DE SAN ANTONIO", "LAS LAJAS", "TAULABE", "SANTA ROSA DE COPAN", "CABAÑAS", "CONCEPCION", "COPAN RUINAS", "CORQUIN", "CUCUYAGUA", "DOLORES", "DULCE NOMBRE", "EL PARAISO", "FLORIDA", "LA JIGUA", "LA UNION", "NUEVA ARCADIA", "SAN AGUSTIN", "SAN ANTONIO", "SAN JERONIMO", "SAN JOSE", "SAN JUAN DE OPOA", "SAN NICOLAS", "SAN PEDRO", "SANTA RITA", "TRINIDAD", "VERACRUZ", "SAN PEDRO SULA", "CHOLOMA", "OMOA", "PIMIENTA", "POTRERILLOS", "PUERTO CORTES", "SAN ANTONIO DE CORTES", "SAN FRANCISCO DE YOJOA", "SAN MANUEL", "SANTA CRUZ DE YOJOA", "VILLANUEVA", "LA LIMA", "CHOLUTECA", "APACILAGUA", "CONCEPCION DE MARIA", "DUYURE", "EL CORPUS", "EL TRIUNFO", "MARCOVIA", "MOROLICA", "NAMASIGUE", "OROCUINA", "PESPIRE", "SAN ANTONIO DE FLORES", "SAN ISIDRO", "SAN JOSE", "SAN MARCOS DE COLON", "SANTA ANA DE YUSGUARE", "YUSCARAN", "ALAUCA", "DANLI", "EL PARAISO", "GUINOPE", "JACALEAPA", "LIURE", "MOROCELI", "OROPOLI", "POTRERILLOS", "SAN ANTONIO DE FLORES", "SAN LUCAS", "SAN MATIAS", "SOLEDAD", "TEUPASENTI", "TEXIGUAT", "VADO ANCHO", "YAUYUPE", "TROJES", "DISTRITO CENTRAL", "ALUBAREN", "CEDROS", "CURAREN", "EL PORVENIR", "GUAIMACA", "LA LIBERTAD", "LA VENTA", "LEPATERIQUE", "MARAITA", "MARALE", "NUEVA ARMENIA", "OJOJONA", "ORICA", "REITOCA", "SABANAGRANDE", "SAN ANTONIO DE ORIENTE", "SAN BUENAVENTURA", "SAN IGNACIO", "CANTARRANAS", "SAN MIGUELITO", "SANTA ANA", "SANTA LUCIA", "TALANGA", "TATUMBLA", "VALLE DE ANGELES", "VILLA SAN FRANCISCO", "VALLECILLOS", "PUERTO LEMPIRA", "BRUS LAGUNA", "AHUAS", "JUAN FRANCISCO BULNES", "VILLEDA MORALES", "WAMPUSIRPI", "LA ESPERANZA", "CAMASCA", "COLOMONCAGUA", "CONCEPCION", "DOLORES", "INTIBUCA", "JESUS DE OTORO", "MAGDALENA", "MASAGUARA", "SAN ANTONIO", "SAN ISIDRO", "SAN JUAN", "SAN MARCOS SIERRA","SAN MIGUELITO","SANTA LUCIA","YAMARANGUILA","SAN FRANCISCO DE OPALACA","ROATAN","GUANAJA","JOSE SANTOS GUARDIOLA","UTILA","LA PAZ","AGUANQUETERIQUE","CABAÑAS","CANE","CHINACLA","GUAJIQUIRO","LAUTERIQUE","MARCALA","MERCEDES DE ORIENTE","OPATORO","SAN ANTONIO DEL NORTE","SAN JOSE","SAN JUAN","SAN PEDRO DE TUTULE","SANTA ANA","SANTA ELENA","SANTA MARIA","SANTIAGO DE PURINGLA","YARULA","GRACIAS","BELEN","CANDELARIA","COLOLACA","ERANDIQUE","GUALCINCE","GUARITA","LA CAMPA","LA IGUALA","LAS FLORES","LA UNION","LA VIRTUD","LEPAERA","MAPULACA","PIRAERA","SAN ANDRES","SAN FRANCISCO","SAN JUAN GUARITA","SAN MANUEL COLOHETE","SAN RAFAEL","SAN SEBASTIAN","SANTA CRUZ","TALGUA","TAMBLA","TOMALA","VALLADOLID","VIRGINIA","SAN MARCOS DE CAIQUIN","OCOTEPEQUE","BELEN GUALCHO","CONCEPCION","DOLORES MERENDON","FRATERNIDAD","LA ENCARNACION","LA LABOR","LUCERNA","MERCEDES","SAN FERNANDO","SAN FRANCISCO DEL VALLE","SAN JORGE","SAN MARCOS","SANTA FE","SENSENTI","SINUAPA","JUTICALPA","CAMPAMENTO","CATACAMAS","CONCORDIA","DULCE NOMBRE DE CULMI","EL ROSARIO","ESQUIPULAS DEL NORTE","GUALACO","GUARIZAMA","GUATA","GUAYAPE","JANO","LA UNION","MANGULILE","MANTO","SALAMA","SAN ESTEBAN","SAN FRANCISCO DE BECERRA","SAN FRANCISCO DE LA PAZ","SANTA MARIA DEL REAL","SILCA","YOCON","PATUCA","SANTA BARBARA","ARADA","ATIMA","AZACUALPA","CEGUACA","SAN JOSE DE COLINAS","CONCEPCION DEL NORTE","CONCEPCION DEL SUR","CHINDA","EL NISPERO","GUALALA","ILAMA","MACUELIZO","NARANJITO","NUEVO CELILAC","PETOA","PROTECCION","QUIMISTAN","SAN FRANCISCO DE OJUERA","SAN LUIS","SAN MARCOS","SAN NICOLAS","SAN PEDRO DE ZACAPA","SANTA RITA","SAN VICENTE CENTENARIO","TRINIDAD","LAS VEGAS","NUEVA FRONTERA","NACAOME","ALIANZA","AMAPALA","ARAMECINA","CARIDAD","GOASCORAN","LANGUE","SAN FRANCISCO DE CORAY","SAN LORENZO","YORO","ARENAL","EL NEGRITO","EL PROGRESO","JOCON","MORAZAN","OLANCHITO","SANTA RITA","SULACO","VICTORIA","YORITO" ]

csv_text = File.read("mesas.csv")
csv = CSV.parse(csv_text, headers: true)

last_dept = 0
last_mun = 0

mun_min = nil
mun_max = nil

i = 0

csv.each do |row|
  mun_min = row.to_hash["Mesa"]

  current_dept = row.to_hash["CodCentroVotacion"][0..1]
  if last_dept != current_dept
    puts "Create department #{current_dept}"
    File.open('seed.rb', 'a') do |f|  
      f.puts "departament = Departamento.create(:name=>\"\",:num=>#{current_dept})"  
    end  
    last_dept = current_dept
  end

  current_mun = row.to_hash["CodCentroVotacion"][2..3]
  if last_mun != current_mun
    last_min = mun_min
    puts "Create municipality #{current_mun}"
    last_mun = current_mun
    File.open('seed.rb', 'a') do |f|  
      f.puts ":to_actum => #{last_min.to_i-1})"
      f.puts "Municipio.create(:name=>\"#{l[i]}\",:num=>#{current_mun.to_i},:departamento_id=>department.id, :from_actum => #{last_min.to_i},"  
    end 
    i = i + 1
  end
end