development:
  adapter: postgresql
  database: actashn
  host: localhost
  username: postgres
  password: postgres
  
production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
