development:
  adapter: postgresql
  database: actashn
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
