# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#---- Ejemplo de lo que tiene que generar el script:

# departamento = Departamento.create(:name=>"Atlantida",:num=>1)
#  Municipio.create(:name=>"La Ceiba",:num=>1,:departamento_id=>departamento.id)
#  Municipio.create(:name=>"Tela",:num=>2,:departamento_id=>departamento.id)

# departamento = Departamento.create(:name=>"Otro",:num=>2)
#  Municipio.create(:name=>"Otro 1",:num=>1,:departamento_id=>departamento.id)
#  Municipio.create(:name=>"Otro 2",:num=>2,:departamento_id=>departamento.id)

#--- Y así para los 18 departamentos y todos los municipios... copy pastiate el output aquí para poder correr el rake db:seed en heroku y alimentar de un solo esas tablas

department = Departamento.create(:name=>"ATLANTIDA",:num=>01, :from_actum => 1, :to_actum => 856)
Municipio.create(:name=>"LA CEIBA",:num=>1,:departamento_id=>department.id, :from_actum => 1, :to_actum => 335)
Municipio.create(:name=>"EL PORVENIR",:num=>2,:departamento_id=>department.id, :from_actum => 336, :to_actum => 374)
Municipio.create(:name=>"ESPARTA",:num=>3,:departamento_id=>department.id, :from_actum => 375, :to_actum => 413)
Municipio.create(:name=>"JUTIAPA",:num=>4,:departamento_id=>department.id, :from_actum => 414, :to_actum => 487)
Municipio.create(:name=>"LA MASICA",:num=>5,:departamento_id=>department.id, :from_actum => 488, :to_actum => 554)
Municipio.create(:name=>"SAN FRANCISCO",:num=>6,:departamento_id=>department.id, :from_actum => 555, :to_actum => 582)
Municipio.create(:name=>"TELA",:num=>7,:departamento_id=>department.id, :from_actum => 583, :to_actum => 798)
Municipio.create(:name=>"ARIZONA",:num=>8,:departamento_id=>department.id, :from_actum => 799, :to_actum => 856)
department = Departamento.create(:name=>"COLON",:num=>02, :from_actum => 857, :to_actum => 1456)
Municipio.create(:name=>"TRUJILLO",:num=>1,:departamento_id=>department.id, :from_actum => 857, :to_actum => 972)
Municipio.create(:name=>"BALFATE",:num=>2,:departamento_id=>department.id, :from_actum => 973, :to_actum => 997)
Municipio.create(:name=>"IRIONA",:num=>3,:departamento_id=>department.id, :from_actum => 998, :to_actum => 1021)
Municipio.create(:name=>"LIMON",:num=>4,:departamento_id=>department.id, :from_actum => 1022, :to_actum => 1042)
Municipio.create(:name=>"SABA",:num=>5,:departamento_id=>department.id, :from_actum => 1043, :to_actum => 1117)
Municipio.create(:name=>"SANTA FE",:num=>6,:departamento_id=>department.id, :from_actum => 1118, :to_actum => 1130)
Municipio.create(:name=>"SANTA ROSA AGUAN",:num=>7,:departamento_id=>department.id, :from_actum => 1131, :to_actum => 1144)
Municipio.create(:name=>"SONAGUERA",:num=>8,:departamento_id=>department.id, :from_actum => 1145, :to_actum => 1237)
Municipio.create(:name=>"TOCOA",:num=>9,:departamento_id=>department.id, :from_actum => 1238, :to_actum => 1391)
Municipio.create(:name=>"BONITO ORIENTAL",:num=>10,:departamento_id=>department.id, :from_actum => 1392, :to_actum => 1456)
department = Departamento.create(:name=>"COMAYAGUA",:num=>03, :from_actum => 1457, :to_actum => 2353)
Municipio.create(:name=>"COMAYAGUA",:num=>1,:departamento_id=>department.id, :from_actum => 1457, :to_actum => 1692)
Municipio.create(:name=>"AJUTERIQUE",:num=>2,:departamento_id=>department.id, :from_actum => 1693, :to_actum => 1718)
Municipio.create(:name=>"EL ROSARIO",:num=>3,:departamento_id=>department.id, :from_actum => 1719, :to_actum => 1765)
Municipio.create(:name=>"ESQUIAS",:num=>4,:departamento_id=>department.id, :from_actum => 1766, :to_actum => 1800)
Municipio.create(:name=>"HUMUYA",:num=>5,:departamento_id=>department.id, :from_actum => 1801, :to_actum => 1804)
Municipio.create(:name=>"LA LIBERTAD",:num=>6,:departamento_id=>department.id, :from_actum => 1805, :to_actum => 1852)
Municipio.create(:name=>"LAMANI",:num=>7,:departamento_id=>department.id, :from_actum => 1853, :to_actum => 1869)
Municipio.create(:name=>"LA TRINIDAD",:num=>8,:departamento_id=>department.id, :from_actum => 1870, :to_actum => 1879)
Municipio.create(:name=>"LEJAMANI",:num=>9,:departamento_id=>department.id, :from_actum => 1880, :to_actum => 1892)
Municipio.create(:name=>"MEAMBAR",:num=>10,:departamento_id=>department.id, :from_actum => 1893, :to_actum => 1917)
Municipio.create(:name=>"MINAS DE ORO",:num=>11,:departamento_id=>department.id, :from_actum => 1918, :to_actum => 1946)
Municipio.create(:name=>"OJOS DE AGUA",:num=>12,:departamento_id=>department.id, :from_actum => 1947, :to_actum => 1967)
Municipio.create(:name=>"SAN JERONIMO",:num=>13,:departamento_id=>department.id, :from_actum => 1968, :to_actum => 2012)
Municipio.create(:name=>"SAN JOSE DE COMAYAGUA",:num=>14,:departamento_id=>department.id, :from_actum => 2013, :to_actum => 2029)
Municipio.create(:name=>"SAN JOSE DEL POTRERO",:num=>15,:departamento_id=>department.id, :from_actum => 2030, :to_actum => 2042)
Municipio.create(:name=>"SAN LUIS",:num=>16,:departamento_id=>department.id, :from_actum => 2043, :to_actum => 2064)
Municipio.create(:name=>"SAN SEBASTIAN",:num=>17,:departamento_id=>department.id, :from_actum => 2065, :to_actum => 2072)
Municipio.create(:name=>"SIGUATEPEQUE",:num=>18,:departamento_id=>department.id, :from_actum => 2073, :to_actum => 2237)
Municipio.create(:name=>"VILLA DE SAN ANTONIO",:num=>19,:departamento_id=>department.id, :from_actum => 2238, :to_actum => 2275)
Municipio.create(:name=>"LAS LAJAS",:num=>20,:departamento_id=>department.id, :from_actum => 2276, :to_actum => 2301)
Municipio.create(:name=>"TAULABE",:num=>21,:departamento_id=>department.id, :from_actum => 2302, :to_actum => 2353)
department = Departamento.create(:name=>"COPAN",:num=>04, :from_actum => 2354, :to_actum => 3093)
Municipio.create(:name=>"SANTA ROSA DE COPAN",:num=>1,:departamento_id=>department.id, :from_actum => 2354, :to_actum => 2457)
Municipio.create(:name=>"CABAÑAS",:num=>2,:departamento_id=>department.id, :from_actum => 2458, :to_actum => 2484)
Municipio.create(:name=>"CONCEPCION",:num=>3,:departamento_id=>department.id, :from_actum => 2485, :to_actum => 2501)
Municipio.create(:name=>"COPAN RUINAS",:num=>4,:departamento_id=>department.id, :from_actum => 2502, :to_actum => 2580)
Municipio.create(:name=>"CORQUIN",:num=>5,:departamento_id=>department.id, :from_actum => 2581, :to_actum => 2607)
Municipio.create(:name=>"CUCUYAGUA",:num=>6,:departamento_id=>department.id, :from_actum => 2608, :to_actum => 2640)
Municipio.create(:name=>"DOLORES",:num=>7,:departamento_id=>department.id, :from_actum => 2641, :to_actum => 2652)
Municipio.create(:name=>"DULCE NOMBRE",:num=>8,:departamento_id=>department.id, :from_actum => 2653, :to_actum => 2666)
Municipio.create(:name=>"EL PARAISO",:num=>9,:departamento_id=>department.id, :from_actum => 2667, :to_actum => 2713)
Municipio.create(:name=>"FLORIDA",:num=>10,:departamento_id=>department.id, :from_actum => 2714, :to_actum => 2775)
Municipio.create(:name=>"LA JIGUA",:num=>11,:departamento_id=>department.id, :from_actum => 2776, :to_actum => 2798)
Municipio.create(:name=>"LA UNION",:num=>12,:departamento_id=>department.id, :from_actum => 2799, :to_actum => 2827)
Municipio.create(:name=>"NUEVA ARCADIA",:num=>13,:departamento_id=>department.id, :from_actum => 2828, :to_actum => 2903)
Municipio.create(:name=>"SAN AGUSTIN",:num=>14,:departamento_id=>department.id, :from_actum => 2904, :to_actum => 2912)
Municipio.create(:name=>"SAN ANTONIO",:num=>15,:departamento_id=>department.id, :from_actum => 2913, :to_actum => 2936)
Municipio.create(:name=>"SAN JERONIMO",:num=>16,:departamento_id=>department.id, :from_actum => 2937, :to_actum => 2949)
Municipio.create(:name=>"SAN JOSE",:num=>17,:departamento_id=>department.id, :from_actum => 2950, :to_actum => 2966)
Municipio.create(:name=>"SAN JUAN DE OPOA",:num=>18,:departamento_id=>department.id, :from_actum => 2967, :to_actum => 2985)
Municipio.create(:name=>"SAN NICOLAS",:num=>19,:departamento_id=>department.id, :from_actum => 2986, :to_actum => 3003)
Municipio.create(:name=>"SAN PEDRO",:num=>20,:departamento_id=>department.id, :from_actum => 3004, :to_actum => 3018)
Municipio.create(:name=>"SANTA RITA",:num=>21,:departamento_id=>department.id, :from_actum => 3019, :to_actum => 3071)
Municipio.create(:name=>"TRINIDAD",:num=>22,:departamento_id=>department.id, :from_actum => 3072, :to_actum => 3085)
Municipio.create(:name=>"VERACRUZ",:num=>23,:departamento_id=>department.id, :from_actum => 3086, :to_actum => 3093)
department = Departamento.create(:name=>"CORTES",:num=>05, :from_actum => 3094, :to_actum => 5884)
Municipio.create(:name=>"SAN PEDRO SULA",:num=>1,:departamento_id=>department.id, :from_actum => 3094, :to_actum => 4388)
Municipio.create(:name=>"CHOLOMA",:num=>2,:departamento_id=>department.id, :from_actum => 4389, :to_actum => 4746)
Municipio.create(:name=>"OMOA",:num=>3,:departamento_id=>department.id, :from_actum => 4747, :to_actum => 4847)
Municipio.create(:name=>"PIMIENTA",:num=>4,:departamento_id=>department.id, :from_actum => 4848, :to_actum => 4881)
Municipio.create(:name=>"POTRERILLOS",:num=>5,:departamento_id=>department.id, :from_actum => 4882, :to_actum => 4933)
Municipio.create(:name=>"PUERTO CORTES",:num=>6,:departamento_id=>department.id, :from_actum => 4934, :to_actum => 5179)
Municipio.create(:name=>"SAN ANTONIO DE CORTES",:num=>7,:departamento_id=>department.id, :from_actum => 5180, :to_actum => 5228)
Municipio.create(:name=>"SAN FRANCISCO DE YOJOA",:num=>8,:departamento_id=>department.id, :from_actum => 5229, :to_actum => 5272)
Municipio.create(:name=>"SAN MANUEL",:num=>9,:departamento_id=>department.id, :from_actum => 5273, :to_actum => 5346)
Municipio.create(:name=>"SANTA CRUZ DE YOJOA",:num=>10,:departamento_id=>department.id, :from_actum => 5347, :to_actum => 5494)
Municipio.create(:name=>"VILLANUEVA",:num=>11,:departamento_id=>department.id, :from_actum => 5495, :to_actum => 5709)
Municipio.create(:name=>"LA LIMA",:num=>12,:departamento_id=>department.id, :from_actum => 5710, :to_actum => 5884)
department = Departamento.create(:name=>"CHOLUTECA",:num=>06, :from_actum => 5885, :to_actum => 6826)
Municipio.create(:name=>"CHOLUTECA",:num=>1,:departamento_id=>department.id, :from_actum => 5885, :to_actum => 6172)
Municipio.create(:name=>"APACILAGUA",:num=>2,:departamento_id=>department.id, :from_actum => 6173, :to_actum => 6195)
Municipio.create(:name=>"CONCEPCION DE MARIA",:num=>3,:departamento_id=>department.id, :from_actum => 6196, :to_actum => 6252)
Municipio.create(:name=>"DUYURE",:num=>4,:departamento_id=>department.id, :from_actum => 6253, :to_actum => 6262)
Municipio.create(:name=>"EL CORPUS",:num=>5,:departamento_id=>department.id, :from_actum => 6263, :to_actum => 6307)
Municipio.create(:name=>"EL TRIUNFO",:num=>6,:departamento_id=>department.id, :from_actum => 6308, :to_actum => 6406)
Municipio.create(:name=>"MARCOVIA",:num=>7,:departamento_id=>department.id, :from_actum => 6407, :to_actum => 6494)
Municipio.create(:name=>"MOROLICA",:num=>8,:departamento_id=>department.id, :from_actum => 6495, :to_actum => 6510)
Municipio.create(:name=>"NAMASIGUE",:num=>9,:departamento_id=>department.id, :from_actum => 6511, :to_actum => 6573)
Municipio.create(:name=>"OROCUINA",:num=>10,:departamento_id=>department.id, :from_actum => 6574, :to_actum => 6616)
Municipio.create(:name=>"PESPIRE",:num=>11,:departamento_id=>department.id, :from_actum => 6617, :to_actum => 6690)
Municipio.create(:name=>"SAN ANTONIO DE FLORES",:num=>12,:departamento_id=>department.id, :from_actum => 6691, :to_actum => 6707)
Municipio.create(:name=>"SAN ISIDRO",:num=>13,:departamento_id=>department.id, :from_actum => 6708, :to_actum => 6719)
Municipio.create(:name=>"SAN JOSE",:num=>14,:departamento_id=>department.id, :from_actum => 6720, :to_actum => 6730)
Municipio.create(:name=>"SAN MARCOS DE COLON",:num=>15,:departamento_id=>department.id, :from_actum => 6731, :to_actum => 6795)
Municipio.create(:name=>"SANTA ANA DE YUSGUARE",:num=>16,:departamento_id=>department.id, :from_actum => 6796, :to_actum => 6826)
department = Departamento.create(:name=>"EL PARAISO",:num=>07, :from_actum => 6827, :to_actum => 7698)
Municipio.create(:name=>"YUSCARAN",:num=>1,:departamento_id=>department.id, :from_actum => 6827, :to_actum => 6858)
Municipio.create(:name=>"ALAUCA",:num=>2,:departamento_id=>department.id, :from_actum => 6859, :to_actum => 6884)
Municipio.create(:name=>"DANLI",:num=>3,:departamento_id=>department.id, :from_actum => 6885, :to_actum => 7211)
Municipio.create(:name=>"EL PARAISO",:num=>4,:departamento_id=>department.id, :from_actum => 7212, :to_actum => 7309)
Municipio.create(:name=>"GUINOPE",:num=>5,:departamento_id=>department.id, :from_actum => 7310, :to_actum => 7328)
Municipio.create(:name=>"JACALEAPA",:num=>6,:departamento_id=>department.id, :from_actum => 7329, :to_actum => 7340)
Municipio.create(:name=>"LIURE",:num=>7,:departamento_id=>department.id, :from_actum => 7341, :to_actum => 7366)
Municipio.create(:name=>"MOROCELI",:num=>8,:departamento_id=>department.id, :from_actum => 7367, :to_actum => 7397)
Municipio.create(:name=>"OROPOLI",:num=>9,:departamento_id=>department.id, :from_actum => 7398, :to_actum => 7416)
Municipio.create(:name=>"POTRERILLOS",:num=>10,:departamento_id=>department.id, :from_actum => 7417, :to_actum => 7425)
Municipio.create(:name=>"SAN ANTONIO DE FLORES",:num=>11,:departamento_id=>department.id, :from_actum => 7426, :to_actum => 7439)
Municipio.create(:name=>"SAN LUCAS",:num=>12,:departamento_id=>department.id, :from_actum => 7440, :to_actum => 7458)
Municipio.create(:name=>"SAN MATIAS",:num=>13,:departamento_id=>department.id, :from_actum => 7459, :to_actum => 7470)
Municipio.create(:name=>"SOLEDAD",:num=>14,:departamento_id=>department.id, :from_actum => 7471, :to_actum => 7493)
Municipio.create(:name=>"TEUPASENTI",:num=>15,:departamento_id=>department.id, :from_actum => 7494, :to_actum => 7564)
Municipio.create(:name=>"TEXIGUAT",:num=>16,:departamento_id=>department.id, :from_actum => 7565, :to_actum => 7585)
Municipio.create(:name=>"VADO ANCHO",:num=>17,:departamento_id=>department.id, :from_actum => 7586, :to_actum => 7595)
Municipio.create(:name=>"YAUYUPE",:num=>18,:departamento_id=>department.id, :from_actum => 7596, :to_actum => 7600)
Municipio.create(:name=>"TROJES",:num=>19,:departamento_id=>department.id, :from_actum => 7601, :to_actum => 7698)
department = Departamento.create(:name=>"FRANCISCO MORAZAN",:num=>8, :from_actum => 7699, :to_actum => 10621)
Municipio.create(:name=>"DISTRITO CENTRAL",:num=>1,:departamento_id=>department.id, :from_actum => 7699, :to_actum => 9862)
Municipio.create(:name=>"ALUBAREN",:num=>2,:departamento_id=>department.id, :from_actum => 9863, :to_actum => 9875)
Municipio.create(:name=>"CEDROS",:num=>3,:departamento_id=>department.id, :from_actum => 9876, :to_actum => 9921)
Municipio.create(:name=>"CURAREN",:num=>4,:departamento_id=>department.id, :from_actum => 9922, :to_actum => 9964)
Municipio.create(:name=>"EL PORVENIR",:num=>5,:departamento_id=>department.id, :from_actum => 9965, :to_actum => 10001)
Municipio.create(:name=>"GUAIMACA",:num=>6,:departamento_id=>department.id, :from_actum => 10002, :to_actum => 10063)
Municipio.create(:name=>"LA LIBERTAD",:num=>7,:departamento_id=>department.id, :from_actum => 10064, :to_actum => 10074)
Municipio.create(:name=>"LA VENTA",:num=>8,:departamento_id=>department.id, :from_actum => 10075, :to_actum => 10093)
Municipio.create(:name=>"LEPATERIQUE",:num=>9,:departamento_id=>department.id, :from_actum => 10094, :to_actum => 10131)
Municipio.create(:name=>"MARAITA",:num=>10,:departamento_id=>department.id, :from_actum => 10132, :to_actum => 10148)
Municipio.create(:name=>"MARALE",:num=>11,:departamento_id=>department.id, :from_actum => 10149, :to_actum => 10169)
Municipio.create(:name=>"NUEVA ARMENIA",:num=>12,:departamento_id=>department.id, :from_actum => 10170, :to_actum => 10181)
Municipio.create(:name=>"OJOJONA",:num=>13,:departamento_id=>department.id, :from_actum => 10182, :to_actum => 10208)
Municipio.create(:name=>"ORICA",:num=>14,:departamento_id=>department.id, :from_actum => 10209, :to_actum => 10237)
Municipio.create(:name=>"REITOCA",:num=>15,:departamento_id=>department.id, :from_actum => 10238, :to_actum => 10264)
Municipio.create(:name=>"SABANAGRANDE",:num=>16,:departamento_id=>department.id, :from_actum => 10265, :to_actum => 10309)
Municipio.create(:name=>"SAN ANTONIO DE ORIENTE",:num=>17,:departamento_id=>department.id, :from_actum => 10310, :to_actum => 10336)
Municipio.create(:name=>"SAN BUENAVENTURA",:num=>18,:departamento_id=>department.id, :from_actum => 10337, :to_actum => 10345)
Municipio.create(:name=>"SAN IGNACIO",:num=>19,:departamento_id=>department.id, :from_actum => 10346, :to_actum => 10369)
Municipio.create(:name=>"CANTARRANAS",:num=>20,:departamento_id=>department.id, :from_actum => 10370, :to_actum => 10399)
Municipio.create(:name=>"SAN MIGUELITO",:num=>21,:departamento_id=>department.id, :from_actum => 10400, :to_actum => 10407)
Municipio.create(:name=>"SANTA ANA",:num=>22,:departamento_id=>department.id, :from_actum => 10408, :to_actum => 10433)
Municipio.create(:name=>"SANTA LUCIA",:num=>23,:departamento_id=>department.id, :from_actum => 10434, :to_actum => 10453)
Municipio.create(:name=>"TALANGA",:num=>24,:departamento_id=>department.id, :from_actum => 10454, :to_actum => 10529)
Municipio.create(:name=>"TATUMBLA",:num=>25,:departamento_id=>department.id, :from_actum => 10530, :to_actum => 10544)
Municipio.create(:name=>"VALLE DE ANGELES",:num=>26,:departamento_id=>department.id, :from_actum => 10545, :to_actum => 10580)
Municipio.create(:name=>"VILLA SAN FRANCISCO",:num=>27,:departamento_id=>department.id, :from_actum => 10581, :to_actum => 10603)
Municipio.create(:name=>"VALLECILLOS",:num=>28,:departamento_id=>department.id, :from_actum => 10604, :to_actum => 10621)
department = Departamento.create(:name=>"GRACIAS A DIOS",:num=>9, :from_actum => 10622, :to_actum => 10735)
Municipio.create(:name=>"PUERTO LEMPIRA",:num=>1,:departamento_id=>department.id, :from_actum => 10622, :to_actum => 10680)
Municipio.create(:name=>"BRUS LAGUNA",:num=>2,:departamento_id=>department.id, :from_actum => 10681, :to_actum => 10697)
Municipio.create(:name=>"AHUAS",:num=>3,:departamento_id=>department.id, :from_actum => 10698, :to_actum => 10707)
Municipio.create(:name=>"JUAN FRANCISCO BULNES",:num=>4,:departamento_id=>department.id, :from_actum => 10708, :to_actum => 10716)
Municipio.create(:name=>"VILLEDA MORALES",:num=>5,:departamento_id=>department.id, :from_actum => 10717, :to_actum => 10728)
Municipio.create(:name=>"WAMPUSIRPI",:num=>6,:departamento_id=>department.id, :from_actum => 10729, :to_actum => 10735)
department = Departamento.create(:name=>"INTIBUCA",:num=>10, :from_actum => 10736, :to_actum => 11170)
Municipio.create(:name=>"LA ESPERANZA",:num=>1,:departamento_id=>department.id, :from_actum => 10736, :to_actum => 10762)
Municipio.create(:name=>"CAMASCA",:num=>2,:departamento_id=>department.id, :from_actum => 10763, :to_actum => 10779)
Municipio.create(:name=>"COLOMONCAGUA",:num=>3,:departamento_id=>department.id, :from_actum => 10780, :to_actum => 10815)
Municipio.create(:name=>"CONCEPCION",:num=>4,:departamento_id=>department.id, :from_actum => 10816, :to_actum => 10840)
Municipio.create(:name=>"DOLORES",:num=>5,:departamento_id=>department.id, :from_actum => 10841, :to_actum => 10850)
Municipio.create(:name=>"INTIBUCA",:num=>6,:departamento_id=>department.id, :from_actum => 10851, :to_actum => 10938)
Municipio.create(:name=>"JESUS DE OTORO",:num=>7,:departamento_id=>department.id, :from_actum => 10939, :to_actum => 10992)
Municipio.create(:name=>"MAGDALENA",:num=>8,:departamento_id=>department.id, :from_actum => 10993, :to_actum => 11002)
Municipio.create(:name=>"MASAGUARA",:num=>9,:departamento_id=>department.id, :from_actum => 11003, :to_actum => 11030)
Municipio.create(:name=>"SAN ANTONIO",:num=>10,:departamento_id=>department.id, :from_actum => 11031, :to_actum => 11045)
Municipio.create(:name=>"SAN ISIDRO",:num=>11,:departamento_id=>department.id, :from_actum => 11046, :to_actum => 11053)
Municipio.create(:name=>"SAN JUAN",:num=>12,:departamento_id=>department.id, :from_actum => 11054, :to_actum => 11076)
Municipio.create(:name=>"SAN MARCOS SIERRA",:num=>13,:departamento_id=>department.id, :from_actum => 11077, :to_actum => 11092)
Municipio.create(:name=>"SAN MIGUELITO",:num=>14,:departamento_id=>department.id, :from_actum => 11093, :to_actum => 11105)
Municipio.create(:name=>"SANTA LUCIA",:num=>15,:departamento_id=>department.id, :from_actum => 11106, :to_actum => 11118)
Municipio.create(:name=>"YAMARANGUILA",:num=>16,:departamento_id=>department.id, :from_actum => 11119, :to_actum => 11154)
Municipio.create(:name=>"SAN FRANCISCO DE OPALACA",:num=>17,:departamento_id=>department.id, :from_actum => 11155, :to_actum => 11170)
department = Departamento.create(:name=>"ISLAS DE LA BAHIA",:num=>11, :from_actum => 11171, :to_actum => 11283)
Municipio.create(:name=>"ROATAN",:num=>1,:departamento_id=>department.id, :from_actum => 11171, :to_actum => 11235)
Municipio.create(:name=>"GUANAJA",:num=>2,:departamento_id=>department.id, :from_actum => 11236, :to_actum => 11250)
Municipio.create(:name=>"JOSE SANTOS GUARDIOLA",:num=>3,:departamento_id=>department.id, :from_actum => 11251, :to_actum => 11274)
Municipio.create(:name=>"UTILA",:num=>4,:departamento_id=>department.id, :from_actum => 11275, :to_actum => 11283)
department = Departamento.create(:name=>"LA PAZ",:num=>12, :from_actum => 11284, :to_actum => 11667)
Municipio.create(:name=>"LA PAZ",:num=>1,:departamento_id=>department.id, :from_actum => 11284, :to_actum => 11355)
Municipio.create(:name=>"AGUANQUETERIQUE",:num=>2,:departamento_id=>department.id, :from_actum => 11356, :to_actum => 11368)
Municipio.create(:name=>"CABAÑAS",:num=>3,:departamento_id=>department.id, :from_actum => 11369, :to_actum => 11375)
Municipio.create(:name=>"CANE",:num=>4,:departamento_id=>department.id, :from_actum => 11376, :to_actum => 11383)
Municipio.create(:name=>"CHINACLA",:num=>5,:departamento_id=>department.id, :from_actum => 11384, :to_actum => 11398)
Municipio.create(:name=>"GUAJIQUIRO",:num=>6,:departamento_id=>department.id, :from_actum => 11399, :to_actum => 11426)
Municipio.create(:name=>"LAUTERIQUE",:num=>7,:departamento_id=>department.id, :from_actum => 11427, :to_actum => 11435)
Municipio.create(:name=>"MARCALA",:num=>8,:departamento_id=>department.id, :from_actum => 11436, :to_actum => 11486)
Municipio.create(:name=>"MERCEDES DE ORIENTE",:num=>9,:departamento_id=>department.id, :from_actum => 11487, :to_actum => 11490)
Municipio.create(:name=>"OPATORO",:num=>10,:departamento_id=>department.id, :from_actum => 11491, :to_actum => 11509)
Municipio.create(:name=>"SAN ANTONIO DEL NORTE",:num=>11,:departamento_id=>department.id, :from_actum => 11510, :to_actum => 11517)
Municipio.create(:name=>"SAN JOSE",:num=>12,:departamento_id=>department.id, :from_actum => 11518, :to_actum => 11534)
Municipio.create(:name=>"SAN JUAN",:num=>13,:departamento_id=>department.id, :from_actum => 11535, :to_actum => 11541)
Municipio.create(:name=>"SAN PEDRO DE TUTULE",:num=>14,:departamento_id=>department.id, :from_actum => 11542, :to_actum => 11556)
Municipio.create(:name=>"SANTA ANA",:num=>15,:departamento_id=>department.id, :from_actum => 11557, :to_actum => 11578)
Municipio.create(:name=>"SANTA ELENA",:num=>16,:departamento_id=>department.id, :from_actum => 11579, :to_actum => 11599)
Municipio.create(:name=>"SANTA MARIA",:num=>17,:departamento_id=>department.id, :from_actum => 11600, :to_actum => 11621)
Municipio.create(:name=>"SANTIAGO DE PURINGLA",:num=>18,:departamento_id=>department.id, :from_actum => 11622, :to_actum => 11653)
Municipio.create(:name=>"YARULA",:num=>19,:departamento_id=>department.id, :from_actum => 11654, :to_actum => 11667)
department = Departamento.create(:name=>"LEMPIRA",:num=>13, :from_actum => 11668, :to_actum => 12304)
Municipio.create(:name=>"GRACIAS",:num=>1,:departamento_id=>department.id, :from_actum => 11668, :to_actum => 11744)
Municipio.create(:name=>"BELEN",:num=>2,:departamento_id=>department.id, :from_actum => 11745, :to_actum => 11756)
Municipio.create(:name=>"CANDELARIA",:num=>3,:departamento_id=>department.id, :from_actum => 11757, :to_actum => 11773)
Municipio.create(:name=>"COLOLACA",:num=>4,:departamento_id=>department.id, :from_actum => 11774, :to_actum => 11787)
Municipio.create(:name=>"ERANDIQUE",:num=>5,:departamento_id=>department.id, :from_actum => 11788, :to_actum => 11818)
Municipio.create(:name=>"GUALCINCE",:num=>6,:departamento_id=>department.id, :from_actum => 11819, :to_actum => 11842)
Municipio.create(:name=>"GUARITA",:num=>7,:departamento_id=>department.id, :from_actum => 11843, :to_actum => 11863)
Municipio.create(:name=>"LA CAMPA",:num=>8,:departamento_id=>department.id, :from_actum => 11864, :to_actum => 11876)
Municipio.create(:name=>"LA IGUALA",:num=>9,:departamento_id=>department.id, :from_actum => 11877, :to_actum => 11917)
Municipio.create(:name=>"LAS FLORES",:num=>10,:departamento_id=>department.id, :from_actum => 11918, :to_actum => 11937)
Municipio.create(:name=>"LA UNION",:num=>11,:departamento_id=>department.id, :from_actum => 11938, :to_actum => 11962)
Municipio.create(:name=>"LA VIRTUD",:num=>12,:departamento_id=>department.id, :from_actum => 11963, :to_actum => 11980)
Municipio.create(:name=>"LEPAERA",:num=>13,:departamento_id=>department.id, :from_actum => 11981, :to_actum => 12050)
Municipio.create(:name=>"MAPULACA",:num=>14,:departamento_id=>department.id, :from_actum => 12051, :to_actum => 12061)
Municipio.create(:name=>"PIRAERA",:num=>15,:departamento_id=>department.id, :from_actum => 12062, :to_actum => 12089)
Municipio.create(:name=>"SAN ANDRES",:num=>16,:departamento_id=>department.id, :from_actum => 12090, :to_actum => 12114)
Municipio.create(:name=>"SAN FRANCISCO",:num=>17,:departamento_id=>department.id, :from_actum => 12115, :to_actum => 12133)
Municipio.create(:name=>"SAN JUAN GUARITA",:num=>18,:departamento_id=>department.id, :from_actum => 12134, :to_actum => 12141)
Municipio.create(:name=>"SAN MANUEL COLOHETE",:num=>19,:departamento_id=>department.id, :from_actum => 12142, :to_actum => 12169)
Municipio.create(:name=>"SAN RAFAEL",:num=>20,:departamento_id=>department.id, :from_actum => 12170, :to_actum => 12195)
Municipio.create(:name=>"SAN SEBASTIAN",:num=>21,:departamento_id=>department.id, :from_actum => 12196, :to_actum => 12216)
Municipio.create(:name=>"SANTA CRUZ",:num=>22,:departamento_id=>department.id, :from_actum => 12217, :to_actum => 12230)
Municipio.create(:name=>"TALGUA",:num=>23,:departamento_id=>department.id, :from_actum => 12231, :to_actum => 12250)
Municipio.create(:name=>"TAMBLA",:num=>24,:departamento_id=>department.id, :from_actum => 12251, :to_actum => 12257)
Municipio.create(:name=>"TOMALA",:num=>25,:departamento_id=>department.id, :from_actum => 12258, :to_actum => 12273)
Municipio.create(:name=>"VALLADOLID",:num=>26,:departamento_id=>department.id, :from_actum => 12274, :to_actum => 12284)
Municipio.create(:name=>"VIRGINIA",:num=>27,:departamento_id=>department.id, :from_actum => 12285, :to_actum => 12291)
Municipio.create(:name=>"SAN MARCOS DE CAIQUIN",:num=>28,:departamento_id=>department.id, :from_actum => 12292, :to_actum => 12304)
department = Departamento.create(:name=>"OCOTEPEQUE",:num=>14, :from_actum => 12305, :to_actum => 12594)
Municipio.create(:name=>"OCOTEPEQUE",:num=>1,:departamento_id=>department.id, :from_actum => 12305, :to_actum => 12354)
Municipio.create(:name=>"BELEN GUALCHO",:num=>2,:departamento_id=>department.id, :from_actum => 12355, :to_actum => 12383)
Municipio.create(:name=>"CONCEPCION",:num=>3,:departamento_id=>department.id, :from_actum => 12384, :to_actum => 12394)
Municipio.create(:name=>"DOLORES MERENDON",:num=>4,:departamento_id=>department.id, :from_actum => 12395, :to_actum => 12401)
Municipio.create(:name=>"FRATERNIDAD",:num=>5,:departamento_id=>department.id, :from_actum => 12402, :to_actum => 12407)
Municipio.create(:name=>"LA ENCARNACION",:num=>6,:departamento_id=>department.id, :from_actum => 12408, :to_actum => 12419)
Municipio.create(:name=>"LA LABOR",:num=>7,:departamento_id=>department.id, :from_actum => 12420, :to_actum => 12438)
Municipio.create(:name=>"LUCERNA",:num=>8,:departamento_id=>department.id, :from_actum => 12439, :to_actum => 12450)
Municipio.create(:name=>"MERCEDES",:num=>9,:departamento_id=>department.id, :from_actum => 12451, :to_actum => 12466)
Municipio.create(:name=>"SAN FERNANDO",:num=>10,:departamento_id=>department.id, :from_actum => 12467, :to_actum => 12480)
Municipio.create(:name=>"SAN FRANCISCO DEL VALLE",:num=>11,:departamento_id=>department.id, :from_actum => 12481, :to_actum => 12496)
Municipio.create(:name=>"SAN JORGE",:num=>12,:departamento_id=>department.id, :from_actum => 12497, :to_actum => 12506)
Municipio.create(:name=>"SAN MARCOS",:num=>13,:departamento_id=>department.id, :from_actum => 12507, :to_actum => 12543)
Municipio.create(:name=>"SANTA FE",:num=>14,:departamento_id=>department.id, :from_actum => 12544, :to_actum => 12555)
Municipio.create(:name=>"SENSENTI",:num=>15,:departamento_id=>department.id, :from_actum => 12556, :to_actum => 12577)
Municipio.create(:name=>"SINUAPA",:num=>16,:departamento_id=>department.id, :from_actum => 12578, :to_actum => 12594)
department = Departamento.create(:name=>"OLANCHO",:num=>15, :from_actum => 12595, :to_actum => 13611)
Municipio.create(:name=>"JUTICALPA",:num=>1,:departamento_id=>department.id, :from_actum => 12595, :to_actum => 12807)
Municipio.create(:name=>"CAMPAMENTO",:num=>2,:departamento_id=>department.id, :from_actum => 12808, :to_actum => 12858)
Municipio.create(:name=>"CATACAMAS",:num=>3,:departamento_id=>department.id, :from_actum => 12859, :to_actum => 13059)
Municipio.create(:name=>"CONCORDIA",:num=>4,:departamento_id=>department.id, :from_actum => 13060, :to_actum => 13080)
Municipio.create(:name=>"DULCE NOMBRE DE CULMI",:num=>5,:departamento_id=>department.id, :from_actum => 13081, :to_actum => 13140)
Municipio.create(:name=>"EL ROSARIO",:num=>6,:departamento_id=>department.id, :from_actum => 13141, :to_actum => 13153)
Municipio.create(:name=>"ESQUIPULAS DEL NORTE",:num=>7,:departamento_id=>department.id, :from_actum => 13154, :to_actum => 13170)
Municipio.create(:name=>"GUALACO",:num=>8,:departamento_id=>department.id, :from_actum => 13171, :to_actum => 13213)
Municipio.create(:name=>"GUARIZAMA",:num=>9,:departamento_id=>department.id, :from_actum => 13214, :to_actum => 13232)
Municipio.create(:name=>"GUATA",:num=>10,:departamento_id=>department.id, :from_actum => 13233, :to_actum => 13255)
Municipio.create(:name=>"GUAYAPE",:num=>11,:departamento_id=>department.id, :from_actum => 13256, :to_actum => 13281)
Municipio.create(:name=>"JANO",:num=>12,:departamento_id=>department.id, :from_actum => 13282, :to_actum => 13292)
Municipio.create(:name=>"LA UNION",:num=>13,:departamento_id=>department.id, :from_actum => 13293, :to_actum => 13307)
Municipio.create(:name=>"MANGULILE",:num=>14,:departamento_id=>department.id, :from_actum => 13308, :to_actum => 13328)
Municipio.create(:name=>"MANTO",:num=>15,:departamento_id=>department.id, :from_actum => 13329, :to_actum => 13354)
Municipio.create(:name=>"SALAMA",:num=>16,:departamento_id=>department.id, :from_actum => 13355, :to_actum => 13373)
Municipio.create(:name=>"SAN ESTEBAN",:num=>17,:departamento_id=>department.id, :from_actum => 13374, :to_actum => 13420)
Municipio.create(:name=>"SAN FRANCISCO DE BECERRA",:num=>18,:departamento_id=>department.id, :from_actum => 13421, :to_actum => 13441)
Municipio.create(:name=>"SAN FRANCISCO DE LA PAZ",:num=>19,:departamento_id=>department.id, :from_actum => 13442, :to_actum => 13485)
Municipio.create(:name=>"SANTA MARIA DEL REAL",:num=>20,:departamento_id=>department.id, :from_actum => 13486, :to_actum => 13508)
Municipio.create(:name=>"SILCA",:num=>21,:departamento_id=>department.id, :from_actum => 13509, :to_actum => 13529)
Municipio.create(:name=>"YOCON",:num=>22,:departamento_id=>department.id, :from_actum => 13530, :to_actum => 13551)
Municipio.create(:name=>"PATUCA",:num=>23,:departamento_id=>department.id, :from_actum => 13552, :to_actum => 13611)
department = Departamento.create(:name=>"SANTA BARBARA",:num=>16, :from_actum => 13612, :to_actum => 14544)
Municipio.create(:name=>"SANTA BARBARA",:num=>1,:departamento_id=>department.id, :from_actum => 13612, :to_actum => 13706)
Municipio.create(:name=>"ARADA",:num=>2,:departamento_id=>department.id, :from_actum => 13707, :to_actum => 13729)
Municipio.create(:name=>"ATIMA",:num=>3,:departamento_id=>department.id, :from_actum => 13730, :to_actum => 13762)
Municipio.create(:name=>"AZACUALPA",:num=>4,:departamento_id=>department.id, :from_actum => 13763, :to_actum => 13809)
Municipio.create(:name=>"CEGUACA",:num=>5,:departamento_id=>department.id, :from_actum => 13810, :to_actum => 13822)
Municipio.create(:name=>"SAN JOSE DE COLINAS",:num=>6,:departamento_id=>department.id, :from_actum => 13823, :to_actum => 13873)
Municipio.create(:name=>"CONCEPCION DEL NORTE",:num=>7,:departamento_id=>department.id, :from_actum => 13874, :to_actum => 13896)
Municipio.create(:name=>"CONCEPCION DEL SUR",:num=>8,:departamento_id=>department.id, :from_actum => 13897, :to_actum => 13911)
Municipio.create(:name=>"CHINDA",:num=>9,:departamento_id=>department.id, :from_actum => 13912, :to_actum => 13924)
Municipio.create(:name=>"EL NISPERO",:num=>10,:departamento_id=>department.id, :from_actum => 13925, :to_actum => 13944)
Municipio.create(:name=>"GUALALA",:num=>11,:departamento_id=>department.id, :from_actum => 13945, :to_actum => 13958)
Municipio.create(:name=>"ILAMA",:num=>12,:departamento_id=>department.id, :from_actum => 13959, :to_actum => 13979)
Municipio.create(:name=>"MACUELIZO",:num=>13,:departamento_id=>department.id, :from_actum => 13980, :to_actum => 14047)
Municipio.create(:name=>"NARANJITO",:num=>14,:departamento_id=>department.id, :from_actum => 14048, :to_actum => 14076)
Municipio.create(:name=>"NUEVO CELILAC",:num=>15,:departamento_id=>department.id, :from_actum => 14077, :to_actum => 14092)
Municipio.create(:name=>"PETOA",:num=>16,:departamento_id=>department.id, :from_actum => 14093, :to_actum => 14121)
Municipio.create(:name=>"PROTECCION",:num=>17,:departamento_id=>department.id, :from_actum => 14122, :to_actum => 14149)
Municipio.create(:name=>"QUIMISTAN",:num=>18,:departamento_id=>department.id, :from_actum => 14150, :to_actum => 14230)
Municipio.create(:name=>"SAN FRANCISCO DE OJUERA",:num=>19,:departamento_id=>department.id, :from_actum => 14231, :to_actum => 14246)
Municipio.create(:name=>"SAN LUIS",:num=>20,:departamento_id=>department.id, :from_actum => 14247, :to_actum => 14305)
Municipio.create(:name=>"SAN MARCOS",:num=>21,:departamento_id=>department.id, :from_actum => 14306, :to_actum => 14338)
Municipio.create(:name=>"SAN NICOLAS",:num=>22,:departamento_id=>department.id, :from_actum => 14339, :to_actum => 14367)
Municipio.create(:name=>"SAN PEDRO DE ZACAPA",:num=>23,:departamento_id=>department.id, :from_actum => 14368, :to_actum => 14393)
Municipio.create(:name=>"SANTA RITA",:num=>24,:departamento_id=>department.id, :from_actum => 14394, :to_actum => 14403)
Municipio.create(:name=>"SAN VICENTE CENTENARIO",:num=>25,:departamento_id=>department.id, :from_actum => 14404, :to_actum => 14410)
Municipio.create(:name=>"TRINIDAD",:num=>26,:departamento_id=>department.id, :from_actum => 14411, :to_actum => 14458)
Municipio.create(:name=>"LAS VEGAS",:num=>27,:departamento_id=>department.id, :from_actum => 14459, :to_actum => 14510)
Municipio.create(:name=>"NUEVA FRONTERA",:num=>28,:departamento_id=>department.id, :from_actum => 14511, :to_actum => 14544)
department = Departamento.create(:name=>"VALLE",:num=>17, :from_actum => 14545, :to_actum => 14972)
Municipio.create(:name=>"NACAOME",:num=>1,:departamento_id=>department.id, :from_actum => 14545, :to_actum => 14673)
Municipio.create(:name=>"ALIANZA",:num=>2,:departamento_id=>department.id, :from_actum => 14674, :to_actum => 14699)
Municipio.create(:name=>"AMAPALA",:num=>3,:departamento_id=>department.id, :from_actum => 14700, :to_actum => 14730)
Municipio.create(:name=>"ARAMECINA",:num=>4,:departamento_id=>department.id, :from_actum => 14731, :to_actum => 14751)
Municipio.create(:name=>"CARIDAD",:num=>5,:departamento_id=>department.id, :from_actum => 14752, :to_actum => 14762)
Municipio.create(:name=>"GOASCORAN",:num=>6,:departamento_id=>department.id, :from_actum => 14763, :to_actum => 14804)
Municipio.create(:name=>"LANGUE",:num=>7,:departamento_id=>department.id, :from_actum => 14805, :to_actum => 14858)
Municipio.create(:name=>"SAN FRANCISCO DE CORAY",:num=>8,:departamento_id=>department.id, :from_actum => 14859, :to_actum => 14882)
Municipio.create(:name=>"SAN LORENZO",:num=>9,:departamento_id=>department.id, :from_actum => 14883, :to_actum => 14972)
department = Departamento.create(:name=>"YORO",:num=>18, :from_actum => 14973, :to_actum => 16094)
Municipio.create(:name=>"YORO",:num=>1,:departamento_id=>department.id, :from_actum => 14973, :to_actum => 15130)
Municipio.create(:name=>"ARENAL",:num=>2,:departamento_id=>department.id, :from_actum => 15131, :to_actum => 15148)
Municipio.create(:name=>"EL NEGRITO",:num=>3,:departamento_id=>department.id, :from_actum => 15149, :to_actum => 15232)
Municipio.create(:name=>"EL PROGRESO",:num=>4,:departamento_id=>department.id, :from_actum => 15233, :to_actum => 15596)
Municipio.create(:name=>"JOCON",:num=>5,:departamento_id=>department.id, :from_actum => 15597, :to_actum => 15619)
Municipio.create(:name=>"MORAZAN",:num=>6,:departamento_id=>department.id, :from_actum => 15620, :to_actum => 15705)
Municipio.create(:name=>"OLANCHITO",:num=>7,:departamento_id=>department.id, :from_actum => 15706, :to_actum => 15908)
Municipio.create(:name=>"SANTA RITA",:num=>8,:departamento_id=>department.id, :from_actum => 15909, :to_actum => 15973)
Municipio.create(:name=>"SULACO",:num=>9,:departamento_id=>department.id, :from_actum => 15974, :to_actum => 16008)
Municipio.create(:name=>"VICTORIA",:num=>10,:departamento_id=>department.id, :from_actum => 16009, :to_actum => 16061)
Municipio.create(:name=>"YORITO",:num=>11,:departamento_id=>department.id, :from_actum => 16062, :to_actum => 16094)
